name: agendamento-de-12-horas

on:
  schedule:
    - cron: '0 */12 * * *'  # Agendamento a cada 12 horas (a cada 720 minutos)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Access the folder and perform git pull
        run: |
            cd app/avaliatech-backend  # Acesse a pasta desejada
            git pull  # Execute o git pull para obter as últimas alterações

      - name: Check for Git changes
        id: git-check
        run: |
            git fetch
            if [[ -n $(git diff --name-only HEAD origin/main) ]]; then
            echo "::set-output name=changed::true"
            else
            echo "::set-output name=changed::false"
            fi
        shell: bash

      - name: Build Docker image and run Docker Compose
        if: steps.git-check.outputs.changed == 'true'
        run: |
            # Add the Docker build and Docker Compose steps here (as previously shown)
        working-directory: $GITHUB_WORKSPACE

                # Build Docker image
      - name: Build Docker image
        run: |
            cd avaliatech-backend
            sudo docker build -t avaliatech-backend:latest .
        working-directory: $GITHUB_WORKSPACE

      - name: Build and push Docker image
        working-directory: app/Avaliatech-backend
        run: |
          # Comandos para autenticar no ECR (substitua as variáveis com suas credenciais)
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin 794196173640.dkr.ecr.us-east-1.amazonaws.com
  
          # Comandos para construir e enviar a imagem Docker
          docker build -t 794196173640.dkr.ecr.us-east-1.amazonaws.com/avaliatech-docker/avaliatech-backend:latest .
          docker push 794196173640.dkr.ecr.us-east-1.amazonaws.com/avaliatech-docker/avaliatech-backend:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

        # Run Docker Compose
      - name: Run Docker Compose
        run: |
            cd avaliatech-backend
            docker-compose up -d
        working-directory: $GITHUB_WORKSPACE